# Generated by Django 4.1.6 on 2024-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org-logo/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
