# Generated by Django 4.1.6 on 2024-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_organization_logo_organization_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organizations',
            field=models.ManyToManyField(to='App.organization'),
        ),
    ]
