# Generated by Django 4.1.6 on 2024-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_invitation_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
