# Generated by Django 4.1.6 on 2024-01-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Inactive', 'Inctive')], default='Active', max_length=10),
        ),
    ]
